### ISSUE TITLE
Select all pictures from date

### ISSUE THREAD

**Issue by karlprieb** [stingle/stingle-photos-android#52]
I think that would be great if I could click on the date and select all pictures from that date.
Today I can only select pictures one by one.

![20201102_232316](https://user-images.githubusercontent.com/9200155/97940433-6c8b4880-1d62-11eb-8fb5-6957fd8401db.jpg)

**Comment by AIGeneratedUsername** [comment]
Is selecting **all** photos is missing too? It is a super basic functionality. It is really surprising that such thing may be missing.

**Comment by alexamiryan** [comment]
Select all by date will be implemented. However select all may not, especially in the gallery, because you could potentially have huge number of files there and selecting all may result in shortage of memory.

**Comment by garry-ut99** [comment]
A lack of such an important and basic feature like "Select all" in a file / photo manager, must be a bad joke. Sometimes photos in galleries are splitted into many "day by day" sections and selecting all photos manually by each day section is barely doable, because is too cumebrsome and takes too much time.

For a comparision, [Photok](https://github.com/leonlatsch/Photok) has that feature.

Also mentioned in:
- https://github.com/stingle/stingle-photos-android/issues/144
